### ISSUE TITLE
Instructor Feedback - Week 4 Exercise

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [EliseJava/TheraBilling#2]
Good work! One question:

- [ ] In the dao there is search by last name, will there be any need to search by other fields? If so, it maybe useful to use a more generic search to allow inputting of both a property and a value for searching.  There was an example of this in the demo code here: https://github.com/MadJavaEntJavaSpring2018/week-1-user-display-exercise-pawaitemadisoncollege/blob/65bff916c112f9f814b97ba15a543319164a0cfb/src/main/java/edu/matc/persistence/UserDao.java#L141

**Comment by EliseJava** [comment]
I have implemented the PropertyLike function in my project
