### ISSUE TITLE
Instructor Feedback Week 5 Exercise

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [EliseJava/TheraBilling#3]
Great work @EliseJava! Looks like you've already overridden .equals in your entities and started on the Generic Dao! 

- [x] Finish switching over all your dao unit tests to use the generic dao, once you confirm everything is working, you can get rid of all the daos except the generic dao (and hopefully won't need to write anymore daos)

Keep up the great work!

**Comment by EliseJava** [comment]
GenericDao implemented, and other Dao's deleted

**Comment by EliseJava** [comment]
GenericDao implemented, and other Dao's deleted
