### ISSUE TITLE
Instructor Feedback - Checkpoint 3

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [EliseJava/TheraBilling#6]
Great job getting this up and running on AWS. I know you ran into issues with your EC2 instance - way to persevere!

- [x] Remember to keep your time log up-to-date.
- [x] readme.md needs some updating. There are references to trails, the NOAA service, materialize, etc. Not sure you are really using those?
- [x] Have you found a good web service to use yet? Hopefully in Week 9 you'll be able to start implementing something as we learn more about rest services. Here is one that be worth considering: https://www.programmableweb.com/api/lifepoint-medical-necessity-validation

**Comment by EliseJava** [comment]
Thanks for the feedback Paula.  Timelog and Readme are updates.

The medical billing is a very complicated subject and I decided to substitute the Webservice for something a little more straightforward.  I found a BreezeOMeter service that provides air quality information for your location, and gives advise for people with health sensitivities.
