### ISSUE TITLE
Instructor Feedback Week 9 - REST

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [EliseJava/TheraBilling#7]
Good job implementing a rest service in your project!

- [x] package names generally are not capitalized - change edu.matc.PatientWebService to edu.matc.patientWebService
- [x] review naming standards for Rest resources: https://github.com/EliseJava/TheraBilling/blob/a4b4919eb21b7f7b9b80f63f674e589e53b3ceef/src/main/java/edu/matc/PatientWebService/PatientLetters.java#L14.   Generally the path will be a noun and plural: patients versus patient or letters versus letter.

**Comment by EliseJava** [comment]
Thanks for the feedback, I have implemented these naming standards in my project.
