### ISSUE TITLE
Peer Review Feedback

### ISSUE THREAD

**Issue by HolliNiesen** [EliseJava/TheraBilling#8]
# Design/Code Review 3

#### Reviewer: Holli

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Project Overview**|| |
||Which planned functionality has been met? | Login, Tests, CRU of CRUD, Styling |
|| What planned functionality has not been met? | Deleting |
||Describe the GitHub history and what it demonstrates about the project progress during the semester.| Commits are steady throughout the semester, showing consistent progress since the beginning of class |
||Describe how peer and instructor feedback/recommendations were incorporated into the project.| Issues were closed upon completion, and empty checkboxes were marked when provided |
||Other comments/notes?| Project is looking great! |
|**JSPs**|| |
||Evaluate the JSPs for templating, business logic, data validation, overall look and feel.| No templates. |
||Other comments/notes?| The JSPs are styled very nicely. Could benefit from a navigation bar for easy navigation between pages. |
|**Java code quality**|Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number) <li>single-purpose methods <li>well-structured project <li>descriptive naming of packages, classes, methods, variables <li>classes appropriately-sized  (no monster classes) <li> CPD (copy paste detection, meaning are the same lines of code repeated?) <li>are there candidates for super/subclass relationships, abstract classes, interfaces? <li>are any values hard-coded that should be in a properties file? <li>proper exception handling <li>proper error reporting to the user <li> code documentation | BreezOResponse.java has commented out code. BillingFunctions.java getMonthlyBillingRecords() could maybe be broken up into smaller methods. |Other comments/notes?| Overall, classes look great. |
|**Logging**|Evaluate the use of logging, for example:<li>appropriate use of logging statements in the code for error logging and debugging <li>logging levels used - info, debug, error <li> no occurrences of  System.out.printlns or printStackTrace() <li> logging works on AWS deploy| Logging looks good |Other comments/notes?| |
|**Unit Tests**|Evaluate the unit tests, for example: <li>tests are truly a unit test rather than a high level functional test <li>test data is appropriately cleaned up or handled <li> there is full coverage of methods that perform business logic or utility functions <li>redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After | Tests look good |
||Other comments/notes?| |
|**Security**|Evaluate authentication/authorization:| |
||Is it implemented correctly and working locally as well as on AWS? | Security  is implemented |
||Other comments/notes?| Can update the login fail page |
|**Web Service/API integration**|Evaluate the service/api integration, for example: <li> Which service/api is implemented? <li>How is  error handling of the service implemented? For example, what happens if the service is not available?| BreezeOMeter - has an error message |
||Other comments/notes?| |
|**Independent research topic**| What is the independent research topic?| No independent research topic |
||Is the independent research topic/technique implemented in the project?| n/a |
||Other comments/notes?| |
|**Deployment**| Has the application been successfully deployed to AWS?| |
||Is the hosted application fully functioning?| Yes |
||Other comments/notes?| Nice work! |

**Comment by EliseJava** [comment]
Implemented all the above suggestions.
