### ISSUE TITLE
Instructor Feedback Week 14

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [EliseJava/TheraBilling#9]
I thought a little review before you present this coming week might be helpful!

The following are from taking a look at your application on AWS, so if this isn't the latest code and already fixed please ignore...
- [x] Adding the same styling to your login error page that you have on the rest of your site would be nice for consistency
- [x] Add in an  error page so that 500 errors with the stack trace are not displayed as they reveal information about your site that you may not want anyone to see.

The following are from a review of the master branch in GitHub:
- [x] Looks like some hard-coding that should be replaced with a live service call? https://github.com/EliseJava/TheraBilling/blob/20efc19f76e0229911433f92347c98abaa0eec6c/src/main/java/edu/matc/controller/BreezOResponse.java#L48
- [x] Remember to replace any hard-coded values with a property in a props file - for example the web service url.
- [x] It looks like only /dashboard.jsp is "locked down". What would happen if the a non-logged in user tried to access any of your servlets directly in the browser? Consider restricting access to all servlets and jsps to prevent access.

**Comment by EliseJava** [comment]
Implemented the above changes.
